INSERT INTO post (title, post_url, user_id)
VALUES 
( 'Donec posuere metus vitae ipsum.',
'https://buzzfeed.com/in/imperdiet/et/commodo/vulputate.png',
10 ),
( 'Morbi non quam nec dui luctus rutrum.',
'https://nasa.gov/donec.json',
8 ),
( 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
'https://europa.eu/parturient/montes/nascetur/ridiculus/mus/etiam/vel.aspx',
1 ),
( 'Nunc purus.',
'http://desdev.cn/enim/blandit/mi.jpg',
4 ),
( 'Pellentesque eget nunc.',
'http://google.ca/nam/nulla/integer.aspx',
7 ),
( 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
'https://stanford.edu/consequat.png',
4 ),
( 'In hac habitasse platea dictumst.',
'http://edublogs.org/non/ligula/pellentesque.js',
1 ),
( 'Morbi non quam nec dui luctus rutrum.',
'http://ucla.edu/consequat/nulla.html',
1 ),
( 'Duis ac nibh.',
'http://theguardian.com/dui/vel/nisl/duis/ac/nibh.aspx',
9 ),
( 'Curabitur at ipsum ac tellus semper interdum.',
'https://reverbnation.com/ligula/sit.jpg',
5 ),
( 'In hac habitasse platea dictumst.',
'http://china.com.cn/lectus/vestibulum.json',
3 ),
( 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
'http://networksolutions.com/nam/ultrices/libero/non/mattis/pulvinar.json',
10 ),
( 'Donec dapibus.',
'https://instagram.com/ac/neque/duis/bibendum/morbi/non.xml',
8 ),
( 'Nulla tellus.',
'https://lycos.com/natoque/penatibus/et.html',
3 ),
( 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',
'https://gmpg.org/lorem.jpg',
3 ),
( 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
'https://paginegialle.it/mattis/egestas.jsp',
7 ),
( 'In hac habitasse platea dictumst.',
'http://wikia.com/turpis/eget.jpg',
6 ),
( 'Etiam justo.',
'https://shareasale.com/quis.json',
4 ),
( 'Nulla ut erat id mauris vulputate elementum.',
'http://java.com/diam/neque/vestibulum/eget/vulputate/ut/ultrices.png',
6 ),
( 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
'https://java.com/at/nibh/in.png',
7 )